openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  '/api/v1/events/that-happened-on/{month}/{day}':
    get:
      summary: 'Fetch events that happened on a specific day'
      operationId: fetchEventsThatHappenedOnASpecificDay
      description: "Fetch events that happened on a specific day\nThis endpoint fetches events that happened on a specific day."
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      year: 2000
                      category: births
                      description: 'Logan Sargeant, amerikansk racerförare.'
                    -
                      year: 1992
                      category: births
                      description: 'Tylor Spink, kanadensisk ishockeyspelare.'
                    -
                      year: 1992
                      category: births
                      description: 'Tyson Spink, kanadensisk ishockeyspelare.'
                    -
                      year: 1991
                      category: births
                      description: 'Dennis Everberg, svensk ishockeyspelare.'
                    -
                      year: 1982
                      category: births
                      description: 'Kikkan Randall, amerikansk längdåkare.'
                    -
                      year: 1979
                      category: births
                      description: 'Bob Bryar, amerikansk trummis i bandet My Chemical Romance.'
                    -
                      year: 1977
                      category: births
                      description: 'Donald Trump, Jr., amerikansk affärsman.'
                    -
                      year: 1977
                      category: births
                      description: 'Psy, sydkoreansk sångare, rappare och låtskrivare.'
                    -
                      year: 1974
                      category: births
                      description: 'Mario Aerts, belgisk tävlingscyklist.'
                    -
                      year: 1974
                      category: births
                      description: 'Tony Kanaan, brasiliansk racerförare.'
                    -
                      year: 1971
                      category: births
                      description: 'Heath Shuler, amerikansk demokratisk politiker, kongressledamot 2007–2013.'
                    -
                      year: 1966
                      category: births
                      description: 'Lars Yngve Johansson, svensk manusförfattare, kompositör och musiker.'
                    -
                      year: 1962
                      category: births
                      description: 'Jeff Flake, amerikansk republikansk politiker, senator (Arizona) 2013–2019.'
                    -
                      year: 1959
                      category: births
                      description: 'Val Kilmer, amerikansk skådespelare.'
                    -
                      year: 1958
                      category: births
                      description: 'Peter Hultqvist, svensk socialdemokratisk försvarsminister.'
                    -
                      year: 1958
                      category: births
                      description: 'Bebe Neuwirth, amerikansk skådespelare och dansares.'
                    -
                      year: 1958
                      category: births
                      description: 'Gunilla Persson, svensk-amerikansk fotomodell.'
                    -
                      year: 1954
                      category: births
                      description: 'Alex Salmond, brittisk politiker, ledare för Scottish National Party 1990–2000 och 2004–2014.'
                    -
                      year: 1953
                      category: births
                      description: 'Jane Badler, amerikansk skådespelare.'
                    -
                      year: 1953
                      category: births
                      description: 'James Remar, amerikansk skådespelare.'
                    -
                      year: 1951
                      category: births
                      description: 'Bárbara Carrera, nicaraguansk skådespelare.'
                    -
                      year: 1951
                      category: births
                      description: 'Tom Hamilton, amerikansk musiker, basist i Aerosmith.'
                    -
                      year: 1949
                      category: births
                      description: 'Tom Kite, amerikansk golfspelare.'
                    -
                      year: 1948
                      category: births
                      description: 'Donna Summer, amerikansk sångare.'
                    -
                      year: 1947
                      category: births
                      description: 'Burton Cummings, kanadensisk rocksångare.'
                properties:
                  data:
                    type: array
                    example:
                      -
                        year: 2000
                        category: births
                        description: 'Logan Sargeant, amerikansk racerförare.'
                      -
                        year: 1992
                        category: births
                        description: 'Tylor Spink, kanadensisk ishockeyspelare.'
                      -
                        year: 1992
                        category: births
                        description: 'Tyson Spink, kanadensisk ishockeyspelare.'
                      -
                        year: 1991
                        category: births
                        description: 'Dennis Everberg, svensk ishockeyspelare.'
                      -
                        year: 1982
                        category: births
                        description: 'Kikkan Randall, amerikansk längdåkare.'
                      -
                        year: 1979
                        category: births
                        description: 'Bob Bryar, amerikansk trummis i bandet My Chemical Romance.'
                      -
                        year: 1977
                        category: births
                        description: 'Donald Trump, Jr., amerikansk affärsman.'
                      -
                        year: 1977
                        category: births
                        description: 'Psy, sydkoreansk sångare, rappare och låtskrivare.'
                      -
                        year: 1974
                        category: births
                        description: 'Mario Aerts, belgisk tävlingscyklist.'
                      -
                        year: 1974
                        category: births
                        description: 'Tony Kanaan, brasiliansk racerförare.'
                      -
                        year: 1971
                        category: births
                        description: 'Heath Shuler, amerikansk demokratisk politiker, kongressledamot 2007–2013.'
                      -
                        year: 1966
                        category: births
                        description: 'Lars Yngve Johansson, svensk manusförfattare, kompositör och musiker.'
                      -
                        year: 1962
                        category: births
                        description: 'Jeff Flake, amerikansk republikansk politiker, senator (Arizona) 2013–2019.'
                      -
                        year: 1959
                        category: births
                        description: 'Val Kilmer, amerikansk skådespelare.'
                      -
                        year: 1958
                        category: births
                        description: 'Peter Hultqvist, svensk socialdemokratisk försvarsminister.'
                      -
                        year: 1958
                        category: births
                        description: 'Bebe Neuwirth, amerikansk skådespelare och dansares.'
                      -
                        year: 1958
                        category: births
                        description: 'Gunilla Persson, svensk-amerikansk fotomodell.'
                      -
                        year: 1954
                        category: births
                        description: 'Alex Salmond, brittisk politiker, ledare för Scottish National Party 1990–2000 och 2004–2014.'
                      -
                        year: 1953
                        category: births
                        description: 'Jane Badler, amerikansk skådespelare.'
                      -
                        year: 1953
                        category: births
                        description: 'James Remar, amerikansk skådespelare.'
                      -
                        year: 1951
                        category: births
                        description: 'Bárbara Carrera, nicaraguansk skådespelare.'
                      -
                        year: 1951
                        category: births
                        description: 'Tom Hamilton, amerikansk musiker, basist i Aerosmith.'
                      -
                        year: 1949
                        category: births
                        description: 'Tom Kite, amerikansk golfspelare.'
                      -
                        year: 1948
                        category: births
                        description: 'Donna Summer, amerikansk sångare.'
                      -
                        year: 1947
                        category: births
                        description: 'Burton Cummings, kanadensisk rocksångare.'
                    items:
                      type: object
                      properties:
                        year:
                          type: integer
                          example: 2000
                        category:
                          type: string
                          example: births
                        description:
                          type: string
                          example: 'Logan Sargeant, amerikansk racerförare.'
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                limit:
                  type: integer
                  description: 'Must be at least 1. Must not be greater than 100.'
                  example: 25
                category:
                  type: string
                  description: ''
                  example: births
                  enum:
                    - births
                    - deaths
                    - holidays
                    - regular
                language:
                  type: string
                  description: ''
                  example: sv
                  enum:
                    - en
                    - de
                    - fr
                    - sv
                    - pt
                    - ru
                    - es
                    - ar
                    - bs
      security: []
    parameters:
      -
        in: path
        name: month
        description: 'The month of the events'
        example: 12
        required: true
        schema:
          type: integer
      -
        in: path
        name: day
        description: 'The day of the events'
        example: 31
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
